services:
  - type: static
    name: edunova-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    routes:
      - type: filesystem
      - type: rewrite
        source: "^/(?!.*\\.).*"
        destination: "/index.html"
